linagora/linshare-mobile-flutter-app

bitrise.yml
@hoangdat Please review this. Thanks!
=> Add bitrise CI's build settings

bitrise.yml
@hoangdat Thanks for your review!
=> Update the development provisioning profile to add the new iPhone 11 Pro Max

domain/lib/src/model/authentication/token.dart, domain/lib/src/model/authentication/token_id.dart, domain/lib/src/model/file_info.dart, domain/lib/src/model/password.dart, domain/lib/src/model/user_name.dart, domain/lib/src/state/failure.dart, domain/lib/src/state/success.dart, domain/lib/src/usecases/authentication/authentication_exception.dart, domain/lib/src/usecases/authentication/authentication_view_state.dart, domain/lib/src/usecases/authentication/create_permanent_token_interactor.dart, domain/lib/src/usecases/authentication/credential_view_state.dart, domain/lib/src/usecases/file_picker/file_picker_view_state.dart, domain/lib/src/usecases/myspace/my_space_view_state.dart, domain/lib/src/usecases/remote_exception.dart, domain/lib/src/usecases/upload_file/file_upload_state.dart, domain/pubspec.yaml, lib/presentation/widget/initialize/initialize_widget.dart, lib/presentation/widget/login/login_widget.dart, lib/presentation/widget/myspace/my_space_widget.dart, lib/presentation/widget/upload_file/upload_file_widget.dart
- execute onDispose method from viewModel in widget
- add Equatable library support for POJO data class
@hoangdat please review this
=> linagora/lgs/linshare/products/linshare-mobile-apps#534 LA-534: add Equatable library support for POJO data class

bitrise.yml
@hoangdat Please update your part on this PR.
=> Add flutter test build steps for the CI job

domain/lib/src/extension/uri_extension.dart, domain/lib/src/usecases/authentication/get_credential_interactor.dart, domain/lib/src/usecases/myspace/upload_file_interactor.dart, domain/test/fixture/test_fixture.dart, domain/test/mock/repository/authentication/mock_authentication_repository.dart, domain/test/mock/repository/authentication/mock_credential_repository.dart, domain/test/mock/repository/authentication/mock_document_repository.dart, domain/test/mock/repository/authentication/mock_token_repository.dart, domain/test/usecases/authentication/create_permanent_token_interactor_test.dart, domain/test/usecases/authentication/get_credential_interactor_test.dart, domain/test/usecases/authentication/upload_file_interactor_test.dart
Implement unit test for:
CreatePermanentTokenInteractor
GetCredentialInteractor
UploadFileInteractor
=> linagora/lgs/linshare/products/linshare-mobile-apps#534 LA-534 Domain unit test

lib/presentation/widget/home/home_viewmodel.dart
@manhduc-nguyen please review this fix
=> [LA-544] Fix Init app error after add linter

data/lib/data.dart, data/lib/src/datasource_impl/document_datasource_impl.dart, data/lib/src/network/model/converter/data_from_json_converter.dart, data/lib/src/network/model/converter/datetime_converter.dart, data/lib/src/network/model/response/document_response.dart, data/lib/src/network/remote_exception_thrower.dart, data/lib/src/repository/myspace/document_repository_impl.dart, data/lib/src/util/attribute.dart, data/pubspec.yaml, data/test/document_datasource_impl_test.dart, data/test/fixture/mock/mock_fixtures.dart, data/test/network/linshare_http_client_test.dart, domain/CHANGELOG.md, domain/lib/domain.dart, domain/lib/src/model/document/document.dart, domain/lib/src/model/document/document_id.dart, domain/lib/src/repository/document/document_repository.dart, domain/lib/src/usecases/myspace/get_all_document_interactor.dart, domain/lib/src/usecases/myspace/my_space_exception.dart, domain/lib/src/usecases/remote_exception.dart, domain/test/usecases/myspace/get_all_document_interactor_test.dart, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/network_module.dart, testshared/.gitignore, testshared/.metadata, testshared/lib/fixture/my_space_fixture.dart, testshared/lib/testshared.dart, testshared/pubspec.yaml
- Domain layer + unit test for GetAllDocument
- Data layer + unit test for GetAllDocument
@hoangdat @imGok please review this
=> linagora/lgs/linshare/products/linshare-mobile-apps#539 LA-539 GetAllDocument domain + data layer

lib/presentation/widget/myspace/my_space_widget.dart
Hi @imGok @manhduc-nguyen , I push this because we are not support it in our sprint, and I created a new one to enable it for Android: https://ci.linagora.com/linagora/lgs/linshare/products/linshare-mobile-apps/issues/599. Please check and review for me. thanks
=> disable Download feature

lib/presentation/util/helper/responsive_widget.dart, lib/presentation/widget/myspace/my_space_widget.dart
1st Breakpoint < 640
2nd Breakpoint >= 640
3rd Breakpoint - > 960
=> LA-583 Responsive My Space

assets/images/ic_export_file.svg, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/util/app_image_paths.dart, lib/presentation/view/downloading_file/downloading_file_builder.dart, lib/presentation/widget/initialize_get_it/initialize_viewmodel.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart, pubspec.yaml
@hoangdat @imGok please review this PR
=> linagora/lgs/linshare/products/linshare-mobile-apps#590 LA-590: Export file in iOS presentation

bitrise.yml, lib/main.dart, lib/presentation/localizations/app_localizations.dart, pubspec.yaml
@tnstung @manhduc-nguyen @imGok Please review this PR.
=> Add scripts to generate intl_translation in CI

bitrise.yml
This is to fix the message icon and the message content that pushes to the FT Mobile channel once a build job is done.
=> Fix the message icon and content that CI job pushes to Twake

data/lib/src/datasource/authentication_datasource.dart, data/test/authentication_datasource_test.dart
@hoangdat sorry for the mistake, here is the fix
=> Add 400 Error to Delete Token and test

android/app/src/main/AndroidManifest.xml
@ngohado @imGok @manhduc-nguyen Please review my PR
=> Add Internet permission to run android app in release

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, data/lib/src/datasource_impl/document_datasource_impl.dart, data/pubspec.yaml, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart, pubspec.yaml
- change `targetApi` to 28 to access to Download directory with `WriteStorage permission`
- handling runtime  permission
=> Enable download action to Android app

domain/lib/domain.dart, domain/lib/src/extension/email_validator_string_extension.dart, domain/lib/src/model/autocomplete/autocomplete_result.dart, domain/lib/src/usecases/autocomplete/get_autocomplete_sharing_interactor.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/util/extensions/color_extension.dart, lib/presentation/view/avatar/label_avatar_builder.dart, lib/presentation/widget/upload_file/upload_file_viewmodel.dart, lib/presentation/widget/upload_file/upload_file_widget.dart, pubspec.yaml
=> linagora/lgs/linshare/products/linshare-mobile-apps#584 LA-584: add share suggestion presentation

ios/Podfile, ios/Runner.xcodeproj/project.pbxproj
=> Change iOS version to 0.0.1 + remove unused apple music permission

assets/images/ic_select_all.svg, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/main.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/model/file/selectable_element.dart, lib/presentation/model/file/selected_presentation_file.dart, lib/presentation/redux/actions/my_space_action.dart, lib/presentation/redux/reducers/my_space_reducer.dart, lib/presentation/redux/states/my_space_state.dart, lib/presentation/util/app_image_paths.dart, lib/presentation/util/extensions/color_extension.dart, lib/presentation/view/multiple_selection_bar/document_multiple_selection_action_builder.dart, lib/presentation/view/multiple_selection_bar/multiple_selection_action_builder.dart, lib/presentation/view/multiple_selection_bar/multiple_selection_bar_builder.dart, lib/presentation/widget/initialize_get_it/initialize_viewmodel.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_navigator.dart, lib/presentation/widget/upload_file/upload_file_viewmodel.dart, lib/presentation/widget/upload_file/upload_file_widget.dart, test/fixtures/test_redux_module.dart
=> LA-64 Share multiple files

assets/images/ic_close.svg, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/destination_picker_action.dart, lib/presentation/redux/reducers/app_reducer.dart, lib/presentation/redux/reducers/destination_picker_reducer.dart, lib/presentation/redux/states/destination_picker_state.dart, lib/presentation/util/app_image_paths.dart, lib/presentation/util/extensions/color_extension.dart, lib/presentation/util/router/route_paths.dart, lib/presentation/util/router/router.dart, lib/presentation/widget/destination_picker/destination_picker_action/base_destination_picker_action.dart, lib/presentation/widget/destination_picker/destination_picker_action/copy_destination_picker_action.dart, lib/presentation/widget/destination_picker/destination_picker_action/negative_destination_picker_action.dart, lib/presentation/widget/destination_picker/destination_picker_arguments.dart, lib/presentation/widget/destination_picker/destination_picker_state.dart, lib/presentation/widget/destination_picker/destination_picker_viewmodel.dart, lib/presentation/widget/destination_picker/destination_picker_widget.dart, lib/presentation/widget/home/home_widget.dart, lib/presentation/widget/shared_space/file_surfing/node_surfing_type.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_detail_files_widget.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_navigator.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_widget.dart
=> LA-59: Destination picker

bitrise.yml
@hoangdat @manhduc-nguyen Thanks for your review!
=> Bump up Linshare iOS app to v0.1.0

domain/lib/domain.dart, domain/lib/src/model/sharedspace/shared_space_operation_role.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/reducers/destination_picker_reducer.dart, lib/presentation/widget/destination_picker/destination_picker_arguments.dart, lib/presentation/widget/destination_picker/destination_picker_viewmodel.dart, lib/presentation/widget/destination_picker/destination_picker_widget.dart, lib/presentation/widget/home/home_viewmodel.dart, lib/presentation/widget/home/home_widget.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart
=> LA-61: Copy document presentation

lib/presentation/di/module/app_module.dart, lib/presentation/manager/upload_and_share_file/upload_and_share_file_manager.dart, lib/presentation/model/upload_and_share/upload_and_share_file_state_list.dart, lib/presentation/util/helper/file_helper.dart, test/manager/upload_and_share_file_manager_test.dart
Please review this [https://app.zenhub.com/workspaces/linshare-flutter-5fe04e3547c3510015c66915/issues/linagora/linshare-mobile-flutter-app/86undefined](https://app.zenhub.com/workspaces/linshare-flutter-5fe04e3547c3510015c66915/issues/linagora/linshare-mobile-flutter-app/86undefined)
=> LA-86: Clean data in app storage after upload file

assets/images/ic_delete.svg, domain/lib/domain.dart, domain/lib/src/usecases/myspace/my_space_view_state.dart, domain/lib/src/usecases/myspace/remove_multiple_documents_interactor.dart, domain/test/usecases/myspace/remove_multiple_documents_interactor_test.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/util/app_image_paths.dart, lib/presentation/util/extensions/color_extension.dart, lib/presentation/view/context_menu/context_menu_builder.dart, lib/presentation/view/modal_sheets/confirm_modal_sheet_builder.dart, lib/presentation/widget/home/home_widget.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart
=> LA-108 Delete document in my space presentation

lib/presentation/di/module/widget_module.dart, lib/presentation/redux/reducers/shared_space_reducer.dart, lib/presentation/redux/states/shared_space_state.dart, lib/presentation/redux/states/ui_state.dart, lib/presentation/view/multiple_selection_bar/workgroupnode_multiple_selection_action_builder.dart, lib/presentation/widget/home/home_widget.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_detail_files_widget.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_navigator_widget.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_state.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_widget.dart
=> LA-48 Delete Multiple Work Group Nodes Presentation Layer

lib/presentation/widget/shared_space/file_surfing/workgroup_detail_files_widget.dart
Last item was hidden by upload button
=> Remove Stack from WorkGroupDetails

domain/lib/src/state/success.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/network_connectivity_action.dart, lib/presentation/redux/reducers/app_reducer.dart, lib/presentation/redux/reducers/network_connectivity_reducer.dart, lib/presentation/redux/states/app_state.dart, lib/presentation/redux/states/authentication_state.dart, lib/presentation/redux/states/destination_picker_state.dart, lib/presentation/redux/states/linshare_state.dart, lib/presentation/redux/states/my_space_state.dart, lib/presentation/redux/states/network_connectivity_state.dart, lib/presentation/redux/states/share_state.dart, lib/presentation/redux/states/shared_space_state.dart, lib/presentation/redux/states/ui_state.dart, lib/presentation/redux/states/upload_file_state.dart, lib/presentation/util/extensions/color_extension.dart, lib/presentation/widget/home/home_viewmodel.dart, lib/presentation/widget/home/home_widget.dart, pubspec.yaml, test/redux/network_connectivity_test.dart
=> LA-135: add network state connection observer

lib/presentation/util/local_file_picker.dart
[https://github.com/linagora/linshare-mobile-flutter-app/issues/103#issue-785872733](https://github.com/linagora/linshare-mobile-flutter-app/issues/103#issue-785872733)
=> LA-103: Avoid navigate to upload screen if user not pick any files

lib/presentation/view/dialog/loading_dialog.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart, pubspec.yaml
- Loading dialog in picking files
- update latest version for file_picker
(srr for the screenshot, hard to take that, it is too rapidly)
=> LA-148 Add progress during picking files

android/app/src/main/AndroidManifest.xml, assets/images/ic_arrow_right.svg, domain/lib/src/model/sharedspace/shared_space_operation_role.dart, ios/LinshareShareExtension/Info.plist, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/destination_picker_action.dart, lib/presentation/redux/reducers/destination_picker_reducer.dart, lib/presentation/redux/states/destination_picker_state.dart, lib/presentation/util/app_image_paths.dart, lib/presentation/widget/destination_picker/destination_picker_action/choose_destination_picker_action.dart, lib/presentation/widget/destination_picker/destination_picker_viewmodel.dart, lib/presentation/widget/destination_picker/destination_picker_widget.dart, lib/presentation/widget/home/home_viewmodel.dart, lib/presentation/widget/initialize_get_it/initialize_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_state.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_viewmodel.dart, lib/presentation/widget/upload_file/upload_destination_type.dart, lib/presentation/widget/upload_file/upload_file_arguments.dart, lib/presentation/widget/upload_file/upload_file_manager.dart, lib/presentation/widget/upload_file/upload_file_viewmodel.dart, lib/presentation/widget/upload_file/upload_file_widget.dart
- Config for support share multiple files from outside in Android and iOS
=> LA-63 Upload outside to workgroup

lib/presentation/di/module/app_module.dart, lib/presentation/util/toast_message_handler.dart, lib/presentation/widget/home/home_viewmodel.dart, lib/presentation/widget/home/home_widget.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart
Refer to this bug: [https://github.com/linagora/linshare-mobile-flutter-app/issues/127](https://github.com/linagora/linshare-mobile-flutter-app/issues/127)
=> LA-127: Update file list in MySpace after remove a file

lib/presentation/widget/upload_file/upload_file_widget.dart
Refer to this bug: [https://github.com/linagora/linshare-mobile-flutter-app/issues/174](https://github.com/linagora/linshare-mobile-flutter-app/issues/174)
=> LA-174: Display upload screen correctly when upload from outside

lib/presentation/redux/actions/my_space_action.dart, lib/presentation/redux/online_thunk_action.dart, lib/presentation/redux/reducers/app_reducer.dart, lib/presentation/redux/states/network_connectivity_state.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart
Refer to this bug: [https://github.com/linagora/linshare-mobile-flutter-app/issues/126](https://github.com/linagora/linshare-mobile-flutter-app/issues/126)
=> LA-126: Show error message when remove file in offline mode

lib/presentation/widget/account_details/account_details_viewmodel.dart, lib/presentation/widget/login/login_widget.dart
Refer to this bug: [https://github.com/linagora/linshare-mobile-flutter-app/issues/119](https://github.com/linagora/linshare-mobile-flutter-app/issues/119)
- Hide keyboard when tap outside in login screen
- Show hint text of textField in error authentication state
- Logout immediately when press logout button
=> LA-119: Hide keyboard when tap outside in login screen

lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/localizations/app_localizations.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_viewmodel.dart
Refer to this: [https://github.com/linagora/linshare-mobile-flutter-app/issues/125](https://github.com/linagora/linshare-mobile-flutter-app/issues/125)
=> LA-125: Display file name correctly in confirm delete dialog

lib/presentation/util/toast_message_handler.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart
Refer to this: [https://github.com/linagora/linshare-mobile-flutter-app/issues/138](https://github.com/linagora/linshare-mobile-flutter-app/issues/138)
=> LA-138: Show delete message and reload list after deleted multiple files successfully

assets/images/ic_copy.svg, data/lib/src/datasource/document_datasource.dart, data/lib/src/datasource_impl/document_datasource_impl.dart, data/lib/src/network/linshare_http_client.dart, data/lib/src/repository/myspace/document_repository_impl.dart, data/test/document_datasource_impl_test.dart, domain/lib/domain.dart, domain/lib/src/usecases/myspace/copy_multiple_to_my_space_interactor.dart, domain/lib/src/usecases/myspace/copy_to_my_space_interactor.dart, domain/lib/src/usecases/myspace/my_space_view_state.dart, domain/test/usecases/myspace/copy_to_my_space_interactor_test.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/util/app_image_paths.dart, lib/presentation/util/toast_message_handler.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_widget.dart
=> LA-182 Copy To My Space From Shared Space

lib/presentation/redux/actions/received_share_action.dart, lib/presentation/redux/reducers/received_shares_reducer.dart, lib/presentation/redux/states/received_share_state.dart, lib/presentation/view/multiple_selection_bar/received_share_multiple_selection_action_builder.dart, lib/presentation/widget/received/received_share_viewmodel.dart, lib/presentation/widget/received/received_share_widget.dart
=> LA-184 Multiple received shares copy

lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/redux/actions/functionality_action.dart, lib/presentation/redux/reducers/app_reducer.dart, lib/presentation/redux/reducers/functionality_reducer.dart, lib/presentation/redux/states/app_state.dart, lib/presentation/redux/states/functionality_state.dart, lib/presentation/widget/home/home_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart, lib/presentation/widget/side_menu/side_menu_widget.dart, lib/presentation/widget/upload_file/upload_file_widget.dart
=> LA-191 Functionality presentation layer

data/lib/src/datasource/shared_space_document_datasource.dart, data/lib/src/datasource_impl/shared_space_document_datasource_impl.dart, data/lib/src/repository/sharedspacedocument/shared_space_document_repository_impl.dart, domain/lib/src/repository/sharedspacedocument/shared_space_document_repository.dart, domain/lib/src/usecases/shared_space/download_workgroup_node_interactor.dart, domain/lib/src/usecases/shared_space/shared_space_view_state.dart, domain/test/usecases/shared_space/download_workgroup_node_interactor_test.dart
@manhduc-nguyen @imGok please review it for me. I will try in presentation in meanwhile. Thanks
=> Download files in SharedSpace for Android

data/lib/src/datasource/shared_space_document_datasource.dart, data/lib/src/datasource_impl/shared_space_document_datasource_impl.dart, data/lib/src/repository/sharedspacedocument/shared_space_document_repository_impl.dart, domain/lib/domain.dart, domain/lib/src/usecases/shared_space/download_multiple_node_ios_interactor.dart, domain/lib/src/usecases/shared_space/download_node_ios_interactor.dart, domain/lib/src/usecases/shared_space/shared_space_view_state.dart, domain/test/usecases/shared_space/download_multiple_node_ios_interactor_test.dart, domain/test/usecases/shared_space/download_node_ios_interactor_test.dart, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_widget.dart
=> LA-185: Export files in work group

domain/lib/domain.dart, domain/lib/src/usecases/search_workgroup_node/search_workgroup_node_interactor.dart, domain/lib/src/usecases/search_workgroup_node/search_workgroup_node_view_state.dart, domain/lib/src/usecases/shared_space/shared_space_view_state.dart, domain/test/usecases/search_workgroup_nodes/search_workgroup_nodes_interactor_test.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/states/ui_state.dart, lib/presentation/widget/home/home_app_bar.dart, lib/presentation/widget/home/home_viewmodel.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_detail_files_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_detail_files_widget.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_widget.dart, testshared/lib/fixture/shared_space_document_fixture.dart
=> LA-190 : Search in shared space

domain/lib/domain.dart, domain/lib/src/usecases/search_shared_space_node_nested/search_shared_space_node_nested_interactor.dart, domain/lib/src/usecases/search_shared_space_node_nested/search_shared_space_node_nested_view_state.dart, domain/test/usecases/search_shared_space_node_nested/search_shared_space_node_nested_interactor_test.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/shared_space_action.dart, lib/presentation/redux/reducers/shared_space_reducer.dart, lib/presentation/redux/states/shared_space_state.dart, lib/presentation/redux/states/ui_state.dart, lib/presentation/widget/home/home_app_bar.dart, lib/presentation/widget/home/home_viewmodel.dart, lib/presentation/widget/shared_space/shared_space_viewmodel.dart, lib/presentation/widget/shared_space/shared_space_widget.dart
=> LA-193: Search workgroup

lib/presentation/widget/upload_file/upload_file_widget.dart
=> LA-87 File icon in upload_file_widget

lib/presentation/di/module/widget_module.dart, lib/presentation/widget/account_details/account_details_widget.dart, lib/presentation/widget/home/home_viewmodel.dart, lib/presentation/widget/initialize_get_it/initialize_viewmodel.dart
refer to this bug: [https://github.com/linagora/linshare-mobile-flutter-app/issues/84](https://github.com/linagora/linshare-mobile-flutter-app/issues/84)
=> LA-84: hide loading indicator + avoid go to login screen when network is not available

data/lib/src/datasource/shared_space_document_datasource.dart, data/lib/src/datasource_impl/shared_space_document_datasource_impl.dart, data/lib/src/repository/sharedspacedocument/shared_space_document_repository_impl.dart, domain/lib/domain.dart, domain/lib/src/repository/sharedspacedocument/shared_space_document_repository.dart, domain/lib/src/usecases/shared_space/download_workgroup_node_interactor.dart, domain/test/usecases/shared_space/download_workgroup_node_interactor_test.dart, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_widget.dart
- presentation layer for download nodes
=> LA-186 Download WorkGroupNode in presentation

lib/presentation/util/router/app_navigation.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_widget.dart
refer to this bug [https://github.com/linagora/linshare-mobile-flutter-app/issues/224](https://github.com/linagora/linshare-mobile-flutter-app/issues/224)
=> LA-224: add missing actions to bottom bar and more actions popup

bitrise.yml
Hot fix for #97 
@manhduc-nguyen @tnstung
=> Bump version to v0.4.1

bitrise.yml
bump version to test Android 29
=> Bump version to v0.4.2

data/lib/src/datasource/shared_space_document_datasource.dart, data/lib/src/datasource_impl/shared_space_document_datasource_impl.dart, data/lib/src/repository/sharedspacedocument/shared_space_document_repository_impl.dart, data/test/shared_space_document_datasource_impl_test.dart, domain/lib/domain.dart, domain/lib/src/extension/media_type_extension.dart, domain/lib/src/model/document/document.dart, domain/lib/src/usecases/shared_space/download_preview_work_group_document_interactor.dart, domain/lib/src/usecases/shared_space/download_preview_work_group_document_view_state.dart, domain/test/model/document_extension_test.dart, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/util/extensions/media_type_extension.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_widget.dart, testshared/lib/fixture/shared_space_document_fixture.dart
=> LA-235 : Preview in shared space

android/app/src/main/AndroidManifest.xml, data/lib/data.dart, data/lib/src/datasource/contact_datasource.dart, data/lib/src/datasource_impl/contact_datasource_impl.dart, data/lib/src/repository/contact/contact_repository_impl.dart, data/pubspec.yaml, domain/lib/domain.dart, domain/lib/src/model/contact/contact.dart, domain/lib/src/model/contact/device_contact.dart, domain/lib/src/repository/contact/contact_repository.dart, domain/lib/src/usecases/autocomplete/get_autocomplete_sharing_with_device_contact_interactor.dart, domain/lib/src/usecases/contact/get_device_contact_suggestions_interactor.dart, domain/lib/src/usecases/contact/get_device_contact_suggestions_view_state.dart, domain/test/mock/repository/mock_contact_repository.dart, domain/test/usecases/autocomplete/get_autocomplete_sharing_with_device_contact_interactor_test.dart, domain/test/usecases/contact/get_device_contact_suggestions_interactor_test.dart, ios/Podfile, ios/Runner/Info.plist, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/widget/upload_file/upload_file_viewmodel.dart, testshared/lib/fixture/autocomplete_fixture.dart, testshared/lib/fixture/contact_fixture.dart, testshared/lib/testshared.dart
https://user-images.githubusercontent.com/16035728/112450939-7ea86a80-8d87-11eb-983f-3fb65be42289.mp4
=> LA-228: Share with device contact

domain/lib/domain.dart, domain/lib/src/extension/document_extensions.dart, domain/lib/src/extension/work_group_node_extensions.dart, domain/lib/src/model/operation.dart, domain/lib/src/usecases/shared_space/copy_multiple_files_to_shared_space_interactor.dart, domain/test/usecases/shared_space/copy_multiple_files_to_shared_space_interactor_test.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/destination_picker_action.dart, lib/presentation/redux/reducers/destination_picker_reducer.dart, lib/presentation/redux/states/destination_picker_state.dart, lib/presentation/util/toast_message_handler.dart, lib/presentation/view/context_menu/work_group_document_context_menu_action_builder.dart, lib/presentation/widget/destination_picker/destination_picker_arguments.dart, lib/presentation/widget/destination_picker/destination_picker_viewmodel.dart, lib/presentation/widget/destination_picker/destination_picker_widget.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_viewmodel.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_widget.dart, lib/presentation/widget/upload_file/destination_type.dart, lib/presentation/widget/upload_file/upload_file_viewmodel.dart, lib/presentation/widget/upload_file/upload_file_widget.dart
@manhduc-nguyen @huynguyennovem @dab246 @imGok Please review it
=> [LA-234] Copy nodes to WorkGroup

data/lib/data.dart, data/lib/src/datasource/received_share_datasource.dart, data/lib/src/datasource_impl/received_share_datasource_impl.dart, data/lib/src/network/model/share/received_share_dto.dart, data/lib/src/repository/received/received_share_repository_imp.dart, domain/lib/domain.dart, domain/lib/src/repository/received/received_share_repository.dart, domain/lib/src/usecases/received/download_preview_received_share_interactor.dart, domain/lib/src/usecases/received/download_preview_received_share_view_state.dart, lib/l10n/intl_messages.arb, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/util/toast_message_handler.dart, lib/presentation/view/context_menu/received_share_context_menu_action_builder.dart, lib/presentation/widget/received/received_share_viewmodel.dart, lib/presentation/widget/received/received_share_widget.dart, testshared/lib/fixture/received_share_fixture.dart
Pls review this guys.
https://user-images.githubusercontent.com/80730648/112971834-ceb57180-9179-11eb-8c55-b735bd1a8396.mp4
=> LA-236 Preview file in Received Share

README.md
=> Compatible version for branch maintenance-0.x

domain/lib/src/extension/string_extension.dart, domain/lib/src/usecases/shared_space/get_shared_space_interactor.dart, domain/lib/src/usecases/shared_space/shared_space_view_state.dart, domain/test/usecases/shared_space/get_shared_space_interactor_test.dart, lib/presentation/widget/destination_picker/destination_picker_widget.dart, lib/presentation/widget/shared_space/file_surfing/workgroup_nodes_surfing_viewmodel.dart, lib/presentation/widget/shared_space_details/shared_space_details_viewmodel.dart
https://user-images.githubusercontent.com/80730648/113375298-49100c80-9399-11eb-9c57-74524947d4f7.mp4
=> LA-304 Fix sort file by name in my space and shared space

data/lib/src/datasource/document_datasource.dart, data/lib/src/datasource_impl/document_datasource_impl.dart, data/lib/src/network/linshare_http_client.dart, data/lib/src/repository/myspace/document_repository_impl.dart, data/test/document_datasource_impl_test.dart, domain/lib/domain.dart, domain/lib/src/model/myspace/rename_document_request.dart, domain/lib/src/usecases/myspace/my_space_view_state.dart, domain/lib/src/usecases/myspace/rename_document_interactor.dart, domain/test/usecases/myspace/rename_document_interactor_test.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/util/extensions/validator_failure_extension.dart, lib/presentation/util/toast_message_handler.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart
=> LA-284 Rename file in my space

domain/lib/src/extension/string_extension.dart, lib/presentation/view/context_menu/simple_horizontal_context_menu_action_builder.dart, lib/presentation/widget/upload_file/upload_file_widget.dart
=> Fix bug 252

data/lib/src/datasource_impl/sort_datasource_impl.dart, data/test/sort_datasource_impl_test.dart, domain/lib/domain.dart, domain/lib/src/extension/list_received_share_extension.dart, domain/lib/src/model/sort/order_screen.dart, domain/lib/src/model/sort/sorter.dart, domain/lib/src/usecases/sort/sort_interactor.dart, domain/test/usecases/sort/sort_interactor_test.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/received_share_action.dart, lib/presentation/redux/reducers/received_shares_reducer.dart, lib/presentation/redux/states/received_share_state.dart, lib/presentation/util/extensions/order_by_extension.dart, lib/presentation/view/context_menu/context_menu_builder.dart, lib/presentation/widget/received/received_share_viewmodel.dart, lib/presentation/widget/received/received_share_widget.dart, testshared/lib/fixture/received_share_fixture.dart
=> LA-242 Received Share Sort

domain/lib/domain.dart, domain/lib/src/usecases/search_received_shares/search_received_shares_interactor.dart, domain/lib/src/usecases/search_received_shares/search_received_shares_view_state.dart, domain/test/usecases/search_received_shares/search_received_shares_interactor_test.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/received_share_action.dart, lib/presentation/redux/reducers/received_shares_reducer.dart, lib/presentation/redux/states/received_share_state.dart, lib/presentation/redux/states/ui_state.dart, lib/presentation/widget/home/home_app_bar.dart, lib/presentation/widget/home/home_viewmodel.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/received/received_share_viewmodel.dart, lib/presentation/widget/received/received_share_widget.dart, lib/presentation/widget/shared_space/shared_space_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart, testshared/lib/fixture/received_share_fixture.dart
=> LA-231 Search in received shares

bitrise.yml
@hoangdat please review this PR.
=> Update the version of deploy-to-itunesconnect-application-loader step in iOS release job

data/lib/src/datasource_impl/sort_datasource_impl.dart, data/test/sort_datasource_impl_test.dart, domain/lib/domain.dart, domain/lib/src/extension/list_work_group_extension.dart, domain/lib/src/model/sort/order_screen.dart, domain/lib/src/model/sort/sorter.dart, domain/lib/src/usecases/sort/sort_interactor.dart, domain/test/extension/sorter_extension_test.dart, domain/test/fixture/test_fixture.dart, domain/test/usecases/sort/sort_interactor_test.dart, lib/l10n/intl_messages.arb, lib/presentation/di/module/widget_module.dart, lib/presentation/redux/actions/shared_space_action.dart, lib/presentation/redux/reducers/shared_space_reducer.dart, lib/presentation/redux/states/shared_space_state.dart, lib/presentation/widget/shared_space/shared_space_viewmodel.dart, lib/presentation/widget/shared_space/shared_space_widget.dart, testshared/lib/fixture/shared_space_fixture.dart
https://user-images.githubusercontent.com/29337364/115869168-b1697f80-a467-11eb-9b7d-205288a2abb4.mp4
=> LA-345 Sort in shared space

bitrise.yml
@hoangdat please review this PR.
=> Switch Bitrise Apple Developer Portal Connection to off in the Deploy to iTunes Connect - Application Loader step

data/lib/src/network/model/response/document_details_response.dart, lib/presentation/redux/reducers/document_details_reducer.dart
Add Types to avoid miss casting
=> Fix Document Details View

data/lib/src/extensions/list_extension.dart
=> LA-105 Fix Auto Suggestion Request

domain/lib/src/model/autocomplete/autocomplete_result.dart, domain/lib/src/model/autocomplete/subtype/shared_space_member_autocomplete_result.dart
=> LA-356 Fix shared space add member full name

data/lib/src/datasource/shared_space_document_datasource.dart, data/lib/src/datasource_impl/shared_space_document_datasource_impl.dart, data/lib/src/network/linshare_http_client.dart, data/lib/src/repository/sharedspacedocument/shared_space_document_repository_impl.dart, data/test/shared_space_document_datasource_impl_test.dart, domain/lib/domain.dart, domain/lib/src/usecases/shared_space/get_shared_space_node_interactor.dart, domain/lib/src/usecases/shared_space/shared_space_view_state.dart, domain/test/usecases/shared_space/get_shared_space_node_interactor_test.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/shared_space_node_details_action.dart, lib/presentation/redux/reducers/app_reducer.dart, lib/presentation/redux/reducers/shared_space_node_details_reducer.dart, lib/presentation/redux/states/app_state.dart, lib/presentation/redux/states/shared_space_node_details_state.dart, lib/presentation/util/extensions/media_type_extension.dart, lib/presentation/util/router/router.dart, lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_document_widget.dart, lib/presentation/widget/shared_space_document/shared_space_node_details/shared_space_node_details_arguments.dart, lib/presentation/widget/shared_space_document/shared_space_node_details/shared_space_node_details_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_node_details/shared_space_node_details_widget.dart
=> LA-364 Work Group Node Details

lib/presentation/widget/home/home_app_bar.dart
=> Align the search area

lib/presentation/view/header/context_menu_header_builder.dart
=> Bug_fixes_align_header_of_context_menu

assets/images/ic_duplicate.svg, domain/lib/src/model/sharedspace/shared_space_operation_role.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/localizations/app_localizations.dart, lib/presentation/util/app_image_paths.dart, lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_document_widget.dart
=> LA-368 Duplicate in Shared Spaces

lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/localizations/app_localizations.dart, lib/presentation/util/toast_message_handler.dart
=> LA-134 Add multiples share message

domain/lib/domain.dart, domain/lib/src/usecases/myspace/duplicate_multiple_files_in_my_space_interactor.dart, domain/lib/src/usecases/myspace/my_space_view_state.dart, domain/test/usecases/myspace/copy_multiple_files_to_my_space_interactor_test.dart, domain/test/usecases/myspace/duplicate_multiple_files_in_my_space_interactor_test.dart, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/util/toast_message_handler.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart
=> LA- 286 Duplicate document

lib/presentation/util/helper/responsive_widget.dart, lib/presentation/view/order_by/order_by_button.dart, lib/presentation/widget/shared_space/shared_space_widget.dart, lib/presentation/widget/shared_space_document/shared_space_document_widget.dart
https://user-images.githubusercontent.com/80730648/116990855-e5f9f880-acfd-11eb-962e-d40aafcddb04.mov
=> LA-371 Apply tablet design for workgroup

domain/lib/domain.dart, domain/lib/src/usecases/shared_space/restore_work_group_document_version_interactor.dart, domain/lib/src/usecases/shared_space/shared_space_view_state.dart, domain/test/usecases/shared_space/restore_work_group_document_version_interactor_test.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/states/shared_space_node_versions_state.dart, lib/presentation/widget/shared_space_document/shared_space_node_versions/shared_space_node_versions_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_node_versions/shared_space_node_versions_widget.dart
=> LA-370 Change version WorkGroup Document 

lib/presentation/widget/shared_space_document/shared_space_document_widget.dart
Reverts linagora/linshare-mobile-flutter-app#391
=> Revert "Touch area increase of Back to Shared Space"

data/lib/data.dart, data/lib/src/datasource_impl/shared_space_datasource_impl.dart, data/lib/src/network/linshare_http_client.dart, data/lib/src/network/model/request/rename_work_group_body_request.dart, data/lib/src/network/model/response/shared_space_node_nested_response.dart, data/lib/src/network/model/sharedspace/versioning_parameter_dto.dart, data/lib/src/repository/sharedspace/shared_space_repository_impl.dart, data/test/shared_space_datasource_impl_test.dart, domain/lib/domain.dart, domain/lib/src/model/sharedspace/rename_work_group_request.dart, domain/lib/src/model/sharedspace/shared_space_node_nested.dart, domain/lib/src/model/sharedspace/versioning_parameter.dart, domain/lib/src/repository/sharedspace/shared_space_repository.dart, domain/lib/src/usecases/shared_space/rename_work_group_interactor.dart, domain/lib/src/usecases/shared_space/shared_space_view_state.dart, domain/test/usecases/shared_space/rename_work_group_interactor_test.dart, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/view/context_menu/work_group_context_menu_action_builder.dart, lib/presentation/view/modal_sheets/edit_text_modal_sheet_builder.dart, lib/presentation/widget/shared_space/shared_space_viewmodel.dart, lib/presentation/widget/shared_space/shared_space_widget.dart, testshared/lib/fixture/shared_space_fixture.dart
=> LA-363 Rename workgroup

lib/presentation/di/module/app_module.dart, lib/presentation/util/helper/responsive_utils.dart, lib/presentation/util/router/router.dart, lib/presentation/view/order_by/order_by_button.dart, lib/presentation/view/transparent_page_route.dart, lib/presentation/widget/destination_picker/destination_picker_widget.dart, lib/presentation/widget/myspace/my_space_widget.dart, lib/presentation/widget/shared_space/shared_space_widget.dart, lib/presentation/widget/shared_space_document/shared_space_document_widget.dart
https://user-images.githubusercontent.com/80730648/117680040-fff27a00-b1da-11eb-9273-7cfbc440e496.mov
=> LA-402 Apply tablet for destination picker screen

data/lib/src/datasource/document_datasource.dart, data/lib/src/datasource_impl/document_datasource_impl.dart, data/lib/src/network/linshare_http_client.dart, data/lib/src/repository/myspace/document_repository_impl.dart, data/test/document_datasource_impl_test.dart, domain/lib/domain.dart, domain/lib/src/model/myspace/edit_description_document_request.dart, domain/lib/src/usecases/myspace/edit_description_document_interactor.dart, domain/lib/src/usecases/myspace/my_space_view_state.dart, domain/test/usecases/myspace/edit_description_document_interactor_test.dart, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/redux/actions/document_details_action.dart, lib/presentation/redux/reducers/document_details_reducer.dart, lib/presentation/redux/states/document_details_state.dart, lib/presentation/widget/myspace/document_details/document_details_viewmodel.dart, lib/presentation/widget/myspace/document_details/document_details_widget.dart
=> LA-281 Edit Description document

bitrise.yml
Create the first PR for the Flutter 2.0 CI job.
=> Create CI environment for Flutter 2.0 in Bitrise

lib/presentation/util/helper/responsive_utils.dart, lib/presentation/view/context_menu/context_menu_builder.dart
https://user-images.githubusercontent.com/80730648/117761329-5c907c00-b251-11eb-8467-5578fbe3b86c.mov
=> LA-405 Apply tablet design for context menu

data/lib/src/network/linshare_http_client.dart, data/lib/src/network/model/request/rename_work_group_body_request.dart, data/lib/src/network/model/sharedspace/versioning_parameter_dto.dart, data/test/shared_space_datasource_impl_test.dart, domain/lib/src/extension/string_extension.dart, domain/lib/src/model/sharedspace/rename_work_group_request.dart, domain/lib/src/model/sharedspace/versioning_parameter.dart, domain/test/usecases/shared_space/rename_work_group_interactor_test.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/util/toast_message_handler.dart, lib/presentation/widget/shared_space/shared_space_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart
**BUG FOUND ON ANDROID**
- App crash when perform share action in context menu
- Repeat toast display in SharedSpace
- Dialog loading still displays when preview file return failed
- Rename workgroup failed
=> Fix bug on master branch for android

lib/presentation/util/extensions/color_extension.dart, lib/presentation/view/text/input_decoration_builder.dart, lib/presentation/widget/login/login_widget.dart
https://user-images.githubusercontent.com/56970970/117961884-d192ad00-b348-11eb-97c7-276ed6a9f158.mp4
=> Set the prefix of the URL field to https: //

data/lib/src/network/linshare_http_client.dart
**DOD**
- Change Endpoint `workGroups` to `sharedSpaces` on v4.0
=> LA-423 Fix bug not found activities of workgroup in shared space

lib/presentation/util/extensions/url_extension.dart, lib/presentation/widget/login/login_viewmodel.dart
https://user-images.githubusercontent.com/80730648/118435582-6d396a00-b709-11eb-9884-13720923bf8c.mov
=> (FIX-BUG) Prefix input url https on LoginScreen

lib/presentation/widget/myspace/document_details/document_details_widget.dart, lib/presentation/widget/shared_space_details/shared_space_details_widget.dart, lib/presentation/widget/shared_space_document/shared_space_node_details/shared_space_node_details_widget.dart
https://user-images.githubusercontent.com/56970970/118525421-5aef1880-b769-11eb-926a-96f4cd617807.mp4
=> Synchronous loading button

lib/presentation/util/helper/responsive_utils.dart, lib/presentation/view/text/linshare_slogan_builder.dart, lib/presentation/widget/login/login_widget.dart
https://user-images.githubusercontent.com/80730648/119100306-00dca480-ba42-11eb-8576-c531a01f528c.mov
=> LA-440 Apply tablet design for Login

lib/presentation/view/context_menu/context_menu_builder.dart
https://user-images.githubusercontent.com/80730648/119126643-7a35c080-ba5d-11eb-84d8-c43e1f7364ef.mov
=> LA-438,439 Fix bug context menu on tablet

domain/lib/src/extension/string_extension.dart, lib/presentation/widget/received/received_share_widget.dart
https://user-images.githubusercontent.com/80730648/119114934-cfb7a080-ba50-11eb-96fa-61a8c3017bf9.mov
=> LA-441 Apply tablet design for Received Share

lib/presentation/widget/login/login_widget.dart
https://user-images.githubusercontent.com/80730648/119341976-a2702a00-bcbe-11eb-83c7-ab968fab60e1.mp4
=> (FIX_BUG) Keyboard override input field password login screen

data/lib/src/datasource/document_datasource.dart, data/lib/src/datasource/received_share_datasource.dart, data/lib/src/datasource/shared_space_document_datasource.dart, data/lib/src/datasource_impl/document_datasource_impl.dart, data/lib/src/datasource_impl/received_share_datasource_impl.dart, data/lib/src/datasource_impl/shared_space_document_datasource_impl.dart, data/lib/src/network/linshare_download_manager.dart, data/lib/src/repository/myspace/document_repository_impl.dart, data/lib/src/repository/received/received_share_repository_imp.dart, data/lib/src/repository/sharedspacedocument/shared_space_document_repository_impl.dart, domain/lib/src/repository/received/received_share_repository.dart, domain/lib/src/repository/sharedspacedocument/shared_space_document_repository.dart, domain/lib/src/usecases/myspace/my_space_view_state.dart, domain/lib/src/usecases/preview_file/download_preview_document_view_state.dart, domain/lib/src/usecases/received/download_preview_received_share_view_state.dart, domain/lib/src/usecases/shared_space/download_preview_work_group_document_view_state.dart, domain/lib/src/usecases/shared_space/shared_space_view_state.dart, domain/test/usecases/download/download_file_ios_interactor_test.dart, domain/test/usecases/download/download_multiple_file_ios_interactor_test.dart, domain/test/usecases/shared_space/download_multiple_node_ios_interactor_test.dart, domain/test/usecases/shared_space/download_node_ios_interactor_test.dart, lib/presentation/util/extensions/uri_extension.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/received/received_share_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_node_versions/shared_space_node_versions_viewmodel.dart
Demo : 
https://user-images.githubusercontent.com/29337364/119331135-33d89f80-bcb1-11eb-9866-7fbce09f985b.mp4
=> Hotifx: Preview file name encoding

lib/presentation/util/helper/responsive_utils.dart, lib/presentation/widget/login/login_widget.dart, lib/presentation/widget/myspace/document_details/document_details_widget.dart, lib/presentation/widget/received/received_share_widget.dart, lib/presentation/widget/shared_space_details/shared_space_details_widget.dart, lib/presentation/widget/shared_space_document/shared_space_node_details/shared_space_node_details_widget.dart
Cherry tablet for login and received share to master
@huynguyennovem @dab246 Please review this
=> Cherry table login

lib/presentation/util/helper/responsive_utils.dart, lib/presentation/widget/destination_picker/destination_picker_widget.dart
**LA-462 Fix bug blank screen when copy files from Workgroup to MySpace in offline mode**
https://user-images.githubusercontent.com/80730648/119472734-afe7eb80-bd74-11eb-8de9-b744db9eeddd.mov
**LA-463 Fix bug pick destination screen is not shown in landscape view**
https://user-images.githubusercontent.com/80730648/119472827-c68e4280-bd74-11eb-87b1-8b764fa9256e.mov
=> LA-462,463 Fix bug destination picker

lib/l10n/intl_vi.arb, lib/presentation/util/helper/responsive_utils.dart, lib/presentation/widget/destination_picker/destination_picker_widget.dart
- fix bug destination
- translate vi
@dab246 @huynguyennovem please review for me
=> Cherry fix destination

lib/presentation/di/module/widget_module.dart, lib/presentation/widget/account_details/account_details_viewmodel.dart
https://user-images.githubusercontent.com/80730648/120287070-162abc00-c2e9-11eb-938e-ec475efc6ff2.mp4
=> Fix bug biometric enabled when logged out

lib/presentation/widget/login/login_widget.dart
=> Hotfix: prevent error message when display OTP screen

domain/lib/src/extension/document_extensions.dart, domain/lib/src/usecases/myspace/get_all_document_interactor.dart, domain/lib/src/usecases/offline_mode/auto_sync_available_offline_document_interactor.dart, domain/lib/src/usecases/offline_mode/auto_sync_available_offline_multiple_document_interactor.dart, domain/lib/src/usecases/offline_mode/enable_available_offline_document_interactor.dart, lib/presentation/manager/offline_mode/auto_sync_offline_manager.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart
**DoD**
- Automatically sync file information when reloading data in MySpace
- Only download new files when the SHA value changes
=> LA-509 Auto Sync available offline document when SHA change in MySpace

data/lib/src/datasource_impl/sort_datasource_impl.dart, data/test/sort_datasource_impl_test.dart, domain/lib/domain.dart, domain/lib/src/extension/boolean_sort_extension.dart, domain/lib/src/extension/list_upload_request_group_extension.dart, domain/lib/src/extension/upload_request_status_extension.dart, domain/lib/src/model/sort/order_by.dart, domain/lib/src/model/sort/sorter.dart, domain/lib/src/model/upload_request_group/upload_request_status.dart, domain/lib/src/usecases/sort/sort_interactor.dart, domain/test/extension/sorter_extension_test.dart, domain/test/fixture/test_fixture.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/upload_request_group_action.dart, lib/presentation/redux/reducers/upload_request_group_reducer.dart, lib/presentation/redux/states/upload_request_group_state.dart, lib/presentation/util/extensions/order_by_extension.dart, lib/presentation/widget/received/received_share_viewmodel.dart, lib/presentation/widget/received/received_share_widget.dart, lib/presentation/widget/upload_request_group/upload_request_group_viewmodel.dart, lib/presentation/widget/upload_request_group/upload_request_group_widget.dart, testshared/lib/fixture/upload_request_group_fixture.dart
=> LA-513 Sort upload request

assets/images/ic_add_recipient.svg, lib/presentation/util/app_image_paths.dart, lib/presentation/util/extensions/color_extension.dart, lib/presentation/util/extensions/upload_request_status_extension.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_widget.dart
Demo video 
https://user-images.githubusercontent.com/29337364/128304388-e3f923cf-e339-4bae-a09f-6539d3252f22.mov
=> LA-515 List recipients in Individual UR

lib/presentation/di/module/widget_module.dart, lib/presentation/widget/home/home_app_bar/home_app_bar_viewmodel.dart, lib/presentation/widget/home/home_app_bar/home_app_bar_widget.dart, lib/presentation/widget/home/home_widget.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart
=> LA-255 Clear Search View After Copying

domain/lib/src/model/functionality/functionality_identifier.dart, lib/presentation/redux/states/functionality_state.dart, lib/presentation/widget/side_menu/side_menu_widget.dart
- Ticket #563 
- Demo:
https://user-images.githubusercontent.com/29337364/128809490-f53d1bf5-4fe7-4394-9f1a-fe378ae63910.mp4
=> LA-563 Functionality upload request

lib/presentation/redux/actions/upload_request_inside_action.dart, lib/presentation/redux/reducers/upload_request_inside_reducer.dart, lib/presentation/redux/states/upload_request_inside_state.dart, lib/presentation/widget/upload_request_inside/upload_request_document_arguments.dart, lib/presentation/widget/upload_request_inside/upload_request_document_type.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_navigator_widget.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_viewmodel.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_widget.dart
- Ticket #518 
- Demo
https://user-images.githubusercontent.com/29337364/128697092-512b3dd3-9f10-4885-aae7-7af5090c7769.mov
=> LA-518 List files of recipient individual Upload Request

data/lib/src/network/linshare_download_manager.dart
=> Fix cancel exception in downloader (#321)

domain/lib/domain.dart, domain/lib/src/usecases/search_upload_request_groups/search_upload_request_groups_interactor.dart, domain/lib/src/usecases/search_upload_request_groups/search_upload_request_groups_view_state.dart, domain/test/usecases/search_upload_request_groups/search_upload_request_groups_interactor_test.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/upload_request_group_action.dart, lib/presentation/redux/reducers/upload_request_group_reducer.dart, lib/presentation/redux/states/ui_state.dart, lib/presentation/redux/states/upload_request_group_state.dart, lib/presentation/view/background_widgets/background_widget_builder.dart, lib/presentation/widget/home/home_app_bar/home_app_bar_widget.dart, lib/presentation/widget/home/home_viewmodel.dart, lib/presentation/widget/upload_request_group/upload_request_group_viewmodel.dart, lib/presentation/widget/upload_request_group/upload_request_group_widget.dart
=> LA-514 Search in upload request

lib/l10n/intl_en.arb, lib/l10n/intl_messages.arb, lib/presentation/localizations/app_localizations.dart
#318  Since it has been reverted I put it again
=> LA-318 Shared space text consistency create

lib/presentation/redux/actions/ui_action.dart, lib/presentation/redux/reducers/ui_reducer.dart, lib/presentation/redux/states/ui_state.dart, lib/presentation/widget/upload_request_group/upload_request_group_viewmodel.dart, lib/presentation/widget/upload_request_group/upload_request_group_widget.dart
=> save last tab index in upload request group view (#560)

data/lib/src/datasource/upload_request_entry_datasource.dart, data/lib/src/datasource_impl/upload_request_entry_datasource_impl.dart, data/lib/src/network/config/endpoint.dart, data/lib/src/repository/upload_request_entry/upload_request_entry_repository_impl.dart, data/test/upload_request_entry_datasource_impl_test.dart, domain/lib/domain.dart, domain/lib/src/repository/upload_request_entry/upload_request_entry_repository.dart, domain/lib/src/usecases/upload_request_entry/download_multiple_upload_request_entry_ios_interactor.dart, domain/lib/src/usecases/upload_request_entry/download_upload_request_entry_interactor.dart, domain/lib/src/usecases/upload_request_entry/download_upload_request_entry_ios_interactor.dart, domain/lib/src/usecases/upload_request_entry/upload_request_entry_view_state.dart, domain/test/fixture/test_fixture.dart, domain/test/usecases/upload_request_entry/download_multiple_node_ios_interactor_test.dart, domain/test/usecases/upload_request_entry/download_node_ios_interactor_test.dart, domain/test/usecases/upload_request_entry/download_upload_request_entry_interactor_test.dart, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/model/file/upload_request_entry_presentation_file.dart, lib/presentation/redux/actions/upload_request_inside_action.dart, lib/presentation/redux/reducers/upload_request_inside_reducer.dart, lib/presentation/redux/states/upload_request_inside_state.dart, lib/presentation/view/context_menu/upload_request_entry_context_menu_action_builder.dart, lib/presentation/view/multiple_selection_bar/uploadrequest_entry_multiple_selection_action_builder.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_viewmodel.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_widget.dart, testshared/lib/fixture/upload_request_entry_fixture.dart
- Ticket #531 
- Demo:
https://user-images.githubusercontent.com/29337364/129165435-edc010af-cb38-4610-8462-5a77e307352c.mp4
https://user-images.githubusercontent.com/29337364/129165607-babd5021-63e4-4643-ad0d-cd370fd4768c.mp4
=> LA-531 Download Upload Request Entry (#531)

domain/lib/domain.dart, domain/lib/src/usecases/search_upload_request_inside/search_upload_request_entries_interactor.dart, domain/lib/src/usecases/search_upload_request_inside/search_upload_request_entries_view_state.dart, domain/test/usecases/search_upload_request_entries/search_upload_request_entries_interactor_test.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/upload_request_inside_action.dart, lib/presentation/redux/reducers/upload_request_inside_reducer.dart, lib/presentation/redux/states/ui_state.dart, lib/presentation/redux/states/upload_request_inside_state.dart, lib/presentation/widget/home/home_app_bar/home_app_bar_viewmodel.dart, lib/presentation/widget/home/home_app_bar/home_app_bar_widget.dart, lib/presentation/widget/home/home_viewmodel.dart, lib/presentation/widget/upload_request_group/created/created_upload_request_group_viewmodel.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_viewmodel.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_widget.dart
@hoangdat Can you verify the ui flow pls ?
- No search bar in Recipients list 
- Only in Upload Entries
=> Search Upload Request Inside (#523) 

domain/lib/domain.dart, domain/lib/src/usecases/upload_request_entry/copy_multiple_files_from_upload_request_entries_to_my_space_interactor.dart, domain/lib/src/usecases/upload_request_entry/upload_request_entry_view_state.dart, domain/test/usecases/upload_request_entry/copy_multiple_files_to_my_space_from_upload_request_entries_interactor_test.dart, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/redux/reducers/upload_request_inside_reducer.dart, lib/presentation/util/toast_message_handler.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_viewmodel.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_widget.dart
=> Copy upload request to my space (#573)

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, data/lib/src/util/device_manager.dart, data/pubspec.yaml, doc/adr/0012-upgrade-android-target-sdk-30.md, lib/presentation/di/module/widget_module.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/received/received_share_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_viewmodel.dart, pubspec.yaml
- Ticket: #237 
- Demo:
https://user-images.githubusercontent.com/29337364/132336395-56950658-0bb5-47b9-bd51-0f527a8ac8fd.mp4
=> LA-237 Upgrade to support Android SDK 30 (Solution 2)

lib/presentation/widget/shared_space_document/shared_space_document_widget.dart
=> add delete button to shared space folder (#593)

lib/presentation/view/common/common_view.dart, lib/presentation/widget/myspace/my_space_widget.dart, lib/presentation/widget/received/received_share_widget.dart, lib/presentation/widget/shared_space/shared_space_widget.dart, lib/presentation/widget/shared_space_document/shared_space_document_widget.dart
=> remove results when null in search view (#421)

lib/presentation/widget/shared_space_details/shared_space_details_widget.dart
=> add scroll widget to shared space details (#464)

lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/localizations/app_localizations.dart, lib/presentation/util/toast_message_handler.dart
=> change all failures copy to my space message (#461)

lib/presentation/manager/upload_and_share_file/upload_and_share_file_manager.dart, lib/presentation/view/background_widgets/background_widget_builder.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart
+ Refresh on background widget
=> Refresh after upload in shared space and my space 

lib/presentation/widget/second_factor_authentication/second_factor_authentication_widget.dart
- Ticket: #473 
- Demo:
https://user-images.githubusercontent.com/29337364/133371437-ade14398-3e24-4b43-9faf-323aa0c84f09.mp4
=> LA-473 Bug fixes 2fa setup landscape not full

lib/presentation/util/helper/responsive_utils.dart
=> add margin top to context menu (#492)

lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/received/received_share_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_node_versions/shared_space_node_versions_viewmodel.dart
=> dispatch no preview when fail (#299)

data/lib/src/datasource/authentication_datasource.dart, data/lib/src/datasource/authentication_sso_datasource.dart, data/lib/src/util/device_manager.dart
- Demo:
https://user-images.githubusercontent.com/29337364/133607058-05720498-f6ee-4cb6-908b-f9e4b41ed0db.mp4
=> LA-477 Add device name to token

lib/presentation/widget/upload_request_creation/upload_request_creation_widget.dart
=> fix overflow in create upload request view

lib/presentation/widget/myspace/my_space_widget.dart
- Ipad 9.7 inch:
- Ipad 12.9 inch
=> LA-630 Fix overflow text on MySpace

lib/presentation/widget/myspace/my_space_viewmodel.dart
- Demo
https://user-images.githubusercontent.com/29337364/134106411-1d0592ac-2c2d-444a-acd9-10742118e2db.mp4
=> LA-81 Fix incorrect screen shown when sharing in uploading process

lib/l10n/intl_messages.arb, lib/presentation/util/helper/input_formatters_utils.dart, lib/presentation/view/modal_sheets/edit_text_modal_sheet_builder.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/shared_space/shared_space_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart
Fix aswell the red field when error msg is null
=> add input formatters utils (#322)

domain/lib/src/extension/string_extension.dart, domain/lib/src/model/sharedspace/shared_space_role_name.dart
- Ticket: #636 
- Demo:
https://user-images.githubusercontent.com/29337364/135054881-ab9c2242-4c67-4344-87c9-0de8e625e380.mp4
=> LA-636 Bug fixes can not access Shared Space

lib/presentation/widget/login/login_widget.dart
=> LA-637 Temporary hiding SSO for releasing v2.0.0

lib/presentation/widget/shared_space/shared_space_widget.dart
- Ticket: #647 
- Demo: 
https://user-images.githubusercontent.com/29337364/135236298-8b1fbe14-5b41-46f9-bc77-b1a032e39ce0.mp4
=> LA-647 Fix workgroup multiple selection

lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/ui_action.dart, lib/presentation/redux/reducers/ui_reducer.dart, lib/presentation/redux/states/ui_state.dart, lib/presentation/widget/home/home_app_bar/home_app_bar_widget.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart, lib/presentation/widget/received/received_share_viewmodel.dart, lib/presentation/widget/received/received_share_widget.dart, lib/presentation/widget/shared_space/shared_space_viewmodel.dart, lib/presentation/widget/shared_space/shared_space_widget.dart, lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_document_widget.dart, lib/presentation/widget/upload_request_group/upload_request_group_viewmodel.dart, lib/presentation/widget/upload_request_group/upload_request_group_widget.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_viewmodel.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_widget.dart
https://user-images.githubusercontent.com/29337364/137117128-d6755c40-cd03-44a0-aa8b-013384f4061d.mp4
=> Update hint text in search bar

lib/presentation/widget/upload_request_creation/upload_request_creation_widget.dart
https://user-images.githubusercontent.com/29337364/137293186-bac50ba1-f971-4f26-80e8-6f3ed233611b.mp4
=> Fix can not create UR

ios/LinshareShareExtension/ShareViewController.swift
https://user-images.githubusercontent.com/80730648/139789337-33bb76be-1ce2-4165-ab3d-d56b4a423c26.mov
=> LA-118 [BUG] Fix unable to export image to LinShare

lib/presentation/widget/home/home_app_bar/home_app_bar_widget.dart
https://user-images.githubusercontent.com/80730648/140453869-eb7789ed-b124-49f0-8ba5-3b703a76012f.mov
=> LA-645 Add info button to the app bar of Workgroup

data/lib/src/datasource/received_share_datasource.dart, data/lib/src/datasource_impl/local_received_share_datasource.dart, data/lib/src/datasource_impl/received_share_datasource_impl.dart, data/lib/src/repository/received/received_share_repository_impl.dart, domain/lib/domain.dart, domain/lib/src/usecases/received/disable_offline_received_share_interactor.dart, domain/lib/src/usecases/received/disable_offline_received_share_view_state.dart, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/util/toast_message_handler.dart, lib/presentation/widget/received/received_share_viewmodel.dart, lib/presentation/widget/received/received_share_widget.dart
https://user-images.githubusercontent.com/80730648/140462911-a7c9734f-7b7e-46a1-bf50-3e485dd73baa.mov
=> LA-695 Disable file offline in ReceivedShare

data/lib/src/datasource/upload_request_entry_datasource.dart, data/lib/src/datasource_impl/upload_request_entry_datasource_impl.dart, data/lib/src/network/linshare_http_client.dart, data/lib/src/repository/upload_request_entry/upload_request_entry_repository_impl.dart, domain/lib/domain.dart, domain/lib/src/usecases/upload_request_entry/remove_multiple_upload_request_entry_interactor.dart, domain/lib/src/usecases/upload_request_entry/remove_upload_request_entry_interactor.dart, domain/lib/src/usecases/upload_request_entry/upload_request_entry_view_state.dart, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/util/toast_message_handler.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_viewmodel.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_widget.dart
https://user-images.githubusercontent.com/80730648/140499448-2c805c56-3b01-4585-9bda-74fbc0fac462.mov
=> LA-606 Delete file in Upload Request

domain/lib/src/model/functionality/functionality_identifier.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/states/functionality_state.dart, lib/presentation/widget/destination_picker/destination_picker_viewmodel.dart, lib/presentation/widget/shared_space/shared_space_viewmodel.dart, lib/presentation/widget/shared_space/shared_space_widget.dart
https://user-images.githubusercontent.com/80730648/142144459-bbe9bef2-26a4-497f-a2ed-ff373c746d5d.mov
=> LA-735 Enable/Disable drive base on functionality

lib/presentation/util/toast_message_handler.dart, lib/presentation/view/modal_sheets/confirm_modal_sheet_builder.dart, lib/presentation/view/multiple_selection_bar/multiple_selection_action_builder.dart, lib/presentation/view/multiple_selection_bar/upload_request_multiple_selection_action_builder.dart, lib/presentation/widget/upload_request_inside/active_close/active_closed_upload_request_inside_view_model.dart, lib/presentation/widget/upload_request_inside/active_close/active_closed_upload_request_inside_widget.dart, lib/presentation/widget/upload_request_inside/archived/archived_upload_request_inside_view_model.dart, lib/presentation/widget/upload_request_inside/archived/archived_upload_request_inside_widget.dart, lib/presentation/widget/upload_request_inside/pending/pending_upload_request_inside_view_model.dart, lib/presentation/widget/upload_request_inside/pending/pending_upload_request_inside_widget.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_viewmodel.dart
https://user-images.githubusercontent.com/80730648/142610669-34a22b0e-cc54-408d-9464-4a8b2fe7fcff.mov
=> LA-599 Archive an Upload request (Recipient)

domain/lib/src/model/sort/order_screen.dart, domain/lib/src/model/sort/sorter.dart, domain/lib/src/usecases/sort/sort_interactor.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/redux/actions/destination_picker_action.dart, lib/presentation/redux/reducers/destination_picker_reducer.dart, lib/presentation/redux/states/destination_picker_state.dart, lib/presentation/view/order_by/order_by_button.dart, lib/presentation/widget/destination_picker/destination_picker_viewmodel.dart, lib/presentation/widget/destination_picker/destination_picker_widget.dart
https://user-images.githubusercontent.com/80730648/142839865-eca81e3c-6388-4c83-9f3d-2341833e5b71.mov
=> LA-643 Order in Destination picker

lib/presentation/widget/upload_request_group/archived/archived_upload_request_group_widget.dart
https://user-images.githubusercontent.com/80730648/142992726-3f0b7916-93a6-446b-81c6-b3d0cee6f03a.mov
=> LA-701 Delete an archived upload request

lib/presentation/util/toast_message_handler.dart, lib/presentation/widget/upload_request_group/active_closed/active_closed_upload_request_group_viewmodel.dart, lib/presentation/widget/upload_request_group/created/created_upload_request_group_viewmodel.dart, lib/presentation/widget/upload_request_group/upload_request_group_tab_common_viewmodel.dart, lib/presentation/widget/upload_request_group_add_recipient/add_recipient_type.dart, lib/presentation/widget/upload_request_group_add_recipient/add_recipients_upload_request_group_viewmodel.dart, lib/presentation/widget/upload_request_group_add_recipient/add_recipients_upload_request_group_widget.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_viewmodel.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_widget.dart
https://user-images.githubusercontent.com/80730648/143013271-388de181-b06f-4023-acfe-a4512ffffbab.mov
=> LA-588 [BUG] Add recipients button inside Individual Upload Request

domain/lib/src/model/sharedspace/shared_space_operation_role.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/view/custom_list_tiles/drive_member_list_tile_builder.dart, lib/presentation/widget/shared_space_details/add_drive_member/add_drive_member_viewmodel.dart, lib/presentation/widget/shared_space_details/add_drive_member/add_drive_member_widget.dart, lib/presentation/widget/shared_space_details/shared_space_details_widget.dart
https://user-images.githubusercontent.com/80730648/144166976-74d26c1b-cc6e-4c8f-a852-f20174ac0bf1.mov
=> LA-720 Delete Drive member

data/lib/src/datasource/authentication_oidc_datasource.dart, data/lib/src/datasource_impl/authentication_oidc_datasource_impl.dart, data/lib/src/local/converter/token_id_converter.dart, data/lib/src/local/model/token_oidc_cache.dart, data/lib/src/repository/authentication/authentication_oidc_repository_impl.dart, data/pubspec.yaml, domain/lib/domain.dart, domain/lib/src/model/authentication/oidc_configuration.dart, domain/lib/src/repository/authentication/authentication_oidc_repository.dart, domain/lib/src/usecases/authentication/delete_token_oidc_interactor.dart, domain/lib/src/usecases/authentication/get_token_oidc_interactor.dart, domain/lib/src/usecases/authentication/log_out_oidc_interactor.dart, domain/lib/src/usecases/authentication/logout_view_state.dart, lib/presentation/di/module/app_module.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/widget/account_details/account_details_viewmodel.dart, lib/presentation/widget/login/login_viewmodel.dart, pubspec.yaml
https://user-images.githubusercontent.com/6462404/144223877-3d9023aa-d43e-4069-9fcf-b9642acc9a77.mov
@huynguyennovem @dab246 Please review this PR.
=> Logout for OIDC

lib/presentation/widget/login/login_widget.dart, lib/presentation/widget/sign_up/sign_up_viewmodel.dart, lib/presentation/widget/sign_up/sign_up_widget.dart
https://user-images.githubusercontent.com/80730648/144394791-399c55e1-6b1a-410d-bc11-5e943c30f813.mov
https://user-images.githubusercontent.com/80730648/144409067-01dd305e-3240-4427-b58b-b4cca26fffd5.mov
=> LA-764 Fix UI bug in SignUp SaaS

lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/localizations/app_localizations.dart
=> Translate vi

domain/lib/src/model/functionality/functionality_identifier.dart, lib/presentation/redux/states/functionality_state.dart, lib/presentation/widget/destination_picker/destination_picker_viewmodel.dart, lib/presentation/widget/myspace/my_space_widget.dart, lib/presentation/widget/received/received_share_widget.dart, lib/presentation/widget/shared_space/shared_space_viewmodel.dart, lib/presentation/widget/shared_space/shared_space_widget.dart, lib/presentation/widget/side_menu/side_menu_widget.dart, lib/presentation/widget/upload_file/upload_file_widget.dart
Test in: https://user.linshare-saas-on-commit.integration-linshare.org/
and https://admin.linshare-saas-on-commit.integration-linshare.org/#/dashboard
https://user-images.githubusercontent.com/6462404/144788840-ffbdb837-3b68-4c4e-9999-dc369e196ee6.mov
=> Shared space functionality in Back-end v5

lib/presentation/redux/actions/workgroup_action.dart, lib/presentation/redux/reducers/destination_picker_reducer.dart, lib/presentation/redux/reducers/workgroup_reducer.dart, lib/presentation/widget/destination_picker/destination_picker_viewmodel.dart, lib/presentation/widget/destination_picker/destination_picker_widget.dart, lib/presentation/widget/shared_space/shared_space_widget.dart, lib/presentation/widget/workgroup/workgroup_viewmodel.dart
https://user-images.githubusercontent.com/80730648/145195058-c27d5645-36d1-4a38-9d2b-0d198e367c27.mov
=> LA-769 Upload file outside to drive

domain/lib/src/model/sharedspace/shared_space_operation_role.dart, lib/presentation/widget/shared_space/shared_space_viewmodel.dart, lib/presentation/widget/shared_space/shared_space_widget.dart
https://user-images.githubusercontent.com/80730648/145328306-8cd17451-4e65-4821-80a1-0af76717ceda.mov
=> LA-779 Delete a drive

lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_messages.arb, lib/l10n/intl_ru.arb, lib/l10n/intl_vi.arb, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/reducers/shared_space_details_reducer.dart, lib/presentation/redux/states/shared_space_details_state.dart, lib/presentation/util/extensions/color_extension.dart, lib/presentation/util/extensions/shared_space_member_extension.dart, lib/presentation/view/custom_list_tiles/shared_space_member_list_tile_builder.dart, lib/presentation/widget/shared_space_details/add_shared_space_member/add_shared_space_member_viewmodel.dart, lib/presentation/widget/shared_space_details/add_shared_space_member/add_shared_space_member_widget.dart, lib/presentation/widget/shared_space_details/shared_space_details_viewmodel.dart, lib/presentation/widget/shared_space_details/shared_space_details_widget.dart, lib/presentation/widget/shared_space_details/workgroup_member_type.dart
https://user-images.githubusercontent.com/80730648/145158683-300e828e-9500-4a4b-b484-ff25cec51283.mov
https://user-images.githubusercontent.com/80730648/145158984-93a3615e-2069-402e-8af5-055695f5d960.mov
=> LA-716 Add external member to workgroup inside a drive

lib/presentation/redux/states/authentication_state.dart, lib/presentation/util/authentication_oidc_config.dart, lib/presentation/widget/login/login_widget.dart
https://user-images.githubusercontent.com/80730648/145749357-79e82d13-fd42-4b66-af53-87cde25d2455.mp4
=> LA-786 Add build-time variable to enable/disable SaaS login and signup

bitrise.yml, lib/presentation/redux/states/authentication_state.dart, lib/presentation/util/authentication_oidc_config.dart, lib/presentation/widget/login/login_widget.dart
- Enable/Disable SaaS functions
=> Release v2.2.2

lib/presentation/widget/home/home_viewmodel.dart
https://user-images.githubusercontent.com/80730648/148010629-40632f22-ab5d-4a26-8889-8439880ca9b6.mov
=> LA-792 [BUG] Fix upload from outside can not upload to shared space

lib/presentation/manager/upload_and_share_file/upload_and_share_file_manager.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/upload_file/upload_file_arguments.dart, lib/presentation/widget/upload_file/upload_file_viewmodel.dart, lib/presentation/widget/upload_file/upload_file_widget.dart, lib/presentation/widget/upload_request_inside/active_close/active_closed_upload_request_inside_widget.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_viewmodel.dart
https://user-images.githubusercontent.com/80730648/148191491-487d787a-8aad-416e-b647-018fc49990a7.mov
=> LA-571 Share files in Upload request

lib/presentation/widget/shared_space_details/shared_space_details_viewmodel.dart, lib/presentation/widget/shared_space_details/shared_space_details_widget.dart
https://user-images.githubusercontent.com/80730648/148203393-a3625525-f2cc-4eda-bcfb-945bf65bb629.mov
=> LA-724 View drive detail

data/lib/src/datasource_impl/sort_datasource_impl.dart, domain/lib/domain.dart, domain/lib/src/extension/list_upload_request_entry_extension.dart, domain/lib/src/model/sort/order_screen.dart, domain/lib/src/model/sort/sorter.dart, domain/lib/src/usecases/sort/sort_interactor.dart, lib/presentation/redux/actions/upload_request_inside_active_closed_action.dart, lib/presentation/redux/actions/upload_request_inside_archived_action.dart, lib/presentation/redux/actions/upload_request_inside_created_action.dart, lib/presentation/redux/reducers/upload_request_inside_active_closed_reducer.dart, lib/presentation/redux/reducers/upload_request_inside_archived_reducer.dart, lib/presentation/redux/reducers/upload_request_inside_created_reducer.dart, lib/presentation/redux/states/upload_request_inside_active_closed_state.dart, lib/presentation/redux/states/upload_request_inside_archived_state.dart, lib/presentation/redux/states/upload_request_inside_created_state.dart, lib/presentation/widget/upload_request_inside/active_close/active_closed_upload_request_inside_view_model.dart, lib/presentation/widget/upload_request_inside/active_close/active_closed_upload_request_inside_widget.dart, lib/presentation/widget/upload_request_inside/archived/archived_upload_request_inside_view_model.dart, lib/presentation/widget/upload_request_inside/archived/archived_upload_request_inside_widget.dart, lib/presentation/widget/upload_request_inside/pending/pending_upload_request_inside_view_model.dart, lib/presentation/widget/upload_request_inside/pending/pending_upload_request_inside_widget.dart
https://user-images.githubusercontent.com/6462404/148549862-7311b2e0-c8ff-4d70-8144-bb80e4e6d0fa.mp4
#524
=> LA-524 Sort upload request entry

data/lib/src/network/model/response/upload_request_response.dart, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/redux/actions/upload_request_recipient_details_action.dart, lib/presentation/redux/reducers/app_reducer.dart, lib/presentation/redux/reducers/upload_request_recipient_details_reducer.dart, lib/presentation/redux/states/app_state.dart, lib/presentation/redux/states/upload_request_recipient_details_state.dart, lib/presentation/util/router/route_paths.dart, lib/presentation/util/router/router.dart, lib/presentation/widget/upload_request_inside/active_close/active_closed_upload_request_inside_widget.dart, lib/presentation/widget/upload_request_inside/archived/archived_upload_request_inside_widget.dart, lib/presentation/widget/upload_request_inside/pending/pending_upload_request_inside_widget.dart, lib/presentation/widget/upload_request_inside/recipient_details/upload_request_recipient_details_arguments.dart, lib/presentation/widget/upload_request_inside/recipient_details/upload_request_recipient_details_viewmodel.dart, lib/presentation/widget/upload_request_inside/recipient_details/upload_request_recipient_details_widget.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_viewmodel.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_widget.dart, test/redux/network_connectivity_test.dart, testshared/lib/fixture/upload_request_fixture.dart
https://user-images.githubusercontent.com/80730648/148749581-c3768a83-630b-4d63-a962-8fb6d97935e8.mov
=> LA-596 View details of an Individual Upload request (Recipient)

data/pubspec.yaml, lib/presentation/di/module/widget_module.dart, lib/presentation/redux/actions/upload_request_file_details_action.dart, lib/presentation/redux/reducers/app_reducer.dart, lib/presentation/redux/reducers/upload_request_file_details_reducer.dart, lib/presentation/redux/states/app_state.dart, lib/presentation/redux/states/upload_request_file_details_state.dart, lib/presentation/util/router/route_paths.dart, lib/presentation/util/router/router.dart, lib/presentation/widget/upload_request_inside/active_close/active_closed_upload_request_inside_widget.dart, lib/presentation/widget/upload_request_inside/archived/archived_upload_request_inside_widget.dart, lib/presentation/widget/upload_request_inside/file_details/upload_request_file_details_arguments.dart, lib/presentation/widget/upload_request_inside/file_details/upload_request_file_details_viewmodel.dart, lib/presentation/widget/upload_request_inside/file_details/upload_request_file_details_widget.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_viewmodel.dart, lib/presentation/widget/upload_request_inside/upload_request_inside_widget.dart, test/redux/network_connectivity_test.dart
https://user-images.githubusercontent.com/80730648/148742434-5b988de5-395a-400d-90d6-6c48a4896a85.mov
=> LA-604 View details of file in Upload request

data/lib/src/repository/authentication/saas_console_repository_impl.dart, domain/lib/src/model/authentication/oidc_configuration.dart, domain/lib/src/model/authentication/saas_type.dart, lib/presentation/util/environment.dart, lib/presentation/widget/login/login_viewmodel.dart, lib/presentation/widget/sign_up/sign_up_viewmodel.dart
=> Add staging environment and build-time variable to config

lib/presentation/util/helper/responsive_utils.dart, lib/presentation/widget/login/login_widget.dart, lib/presentation/widget/sign_up/sign_up_widget.dart
https://user-images.githubusercontent.com/80730648/149465456-9885f36e-9fde-4726-b0c8-72d80878f624.mov
=> LA-819 Login form in tablet view

bitrise.yml
Enable SaaS
@dab246 please review
=> Release v3.1.0

lib/presentation/localizations/app_localizations.dart, lib/presentation/util/helper/responsive_utils.dart, lib/presentation/widget/login/login_widget.dart, lib/presentation/widget/sign_up/sign_up_widget.dart
- BUG
- FIXED
https://user-images.githubusercontent.com/80730648/150281581-b795dcef-fdee-4258-ab6f-c9a3c843c2c3.mp4
=> [BUG] Fix bug overflow pixel on login view

data/lib/src/repository/authentication/saas_console_repository_impl.dart, domain/lib/src/model/authentication/saas_type.dart, lib/presentation/util/environment.dart
=> Add production environment

data/lib/src/local/config/database_config.dart, data/lib/src/local/config/shared_space_table.dart, data/lib/src/local/database_client.dart, data/lib/src/local/model/shared_space_cache.dart, data/lib/src/local/shared_space_document_database_manager.dart
=> LA - Fix syntax error in database for offline mode

lib/presentation/widget/account_details/account_details_widget.dart, pubspec.yaml
=> Change file size to SI unit

lib/presentation/view/modal_sheets/edit_text_modal_sheet_builder.dart, lib/presentation/view/modal_sheets/rename_modal_sheet_builder.dart, lib/presentation/widget/myspace/my_space_viewmodel.dart, lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart
https://user-images.githubusercontent.com/6462404/174237455-45fa8e27-14fc-4767-b1d6-a19e6a5a4e08.mov
https://user-images.githubusercontent.com/6462404/174237527-dc6c52f8-09c3-4266-8b73-aaf02f832c57.mov
=> LA-880 Rename file without change extension

data/lib/src/datasource_impl/functionality_datasource_impl.dart, data/lib/src/datasource_impl/upload_request_group_datasource_impl.dart, domain/lib/src/model/functionality/functionality_identifier.dart, domain/lib/src/usecases/upload_request_group/add_new_upload_request_interactor.dart, domain/lib/src/usecases/upload_request_group/upload_request_group_exception.dart, domain/lib/src/usecases/upload_request_group/upload_request_group_view_state.dart, lib/l10n/intl_messages.arb, lib/presentation/di/module/widget_module.dart, lib/presentation/localizations/app_localizations.dart, lib/presentation/widget/upload_request_creation/upload_request_creation_viewmodel.dart
https://user-images.githubusercontent.com/6462404/176884682-0ba42587-2eb7-4c93-aa73-2689a5b8f74b.mp4
=> LA-870 Handle UploadRequestLimitation when create UploadRequest

android/app/src/main/kotlin/com/linagora/flutter/linshare_flutter_app/MainActivity.kt, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, data/lib/src/extensions/biometric_type_extension.dart, data/lib/src/util/local_biometric_service.dart, data/pubspec.yaml, domain/lib/src/model/biometric_authentication/biometric_kind.dart, domain/lib/src/usecases/biometric_auhentication/authentication_biometric_interactor.dart, lib/main.dart, lib/presentation/util/generate_password_utils.dart, lib/presentation/widget/biometric_authentication/biometric_authentication_setting_widget.dart, pubspec.yaml
https://user-images.githubusercontent.com/6462404/180984707-875de02c-04ee-4298-b3db-7d6396d155f0.mov
=> update the min length of password for signing up account to 32

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/xml/network_security_config.xml, bitrise.yml, lib/l10n/intl_eo.arb, lib/l10n/intl_fr.arb, lib/l10n/intl_vi.arb
- Translation updated
- Support User CA
=> Release v3.6.3

.github/workflows/ci.yaml, .github/workflows/deploy.yaml, android/Gemfile, android/app/build.gradle, android/fastlane/Appfile, android/fastlane/Fastfile, android/fastlane/README.md, ios/Gemfile, ios/Runner.xcodeproj/project.pbxproj, ios/fastlane/Appfile, ios/fastlane/Fastfile, ios/fastlane/README.md
This PR adds support for Github Actions to run CD on our application.
=> Initial workflow for CD

lib/presentation/widget/myspace/my_space_widget.dart, lib/presentation/widget/received/received_share_widget.dart, lib/presentation/widget/shared_space_document/shared_space_document_widget.dart
https://user-images.githubusercontent.com/6462404/198232895-a2971e23-2055-47f7-aaf1-014794704aca.mp4
=> Export file one by one in both iOS and Android

.github/workflows/analyze-test.yaml, .github/workflows/ci.yaml, .github/workflows/release.yaml, prebuild.sh
This will align workflows to match Tmail and Twake
=> Refactored workflow to a better structure

.github/workflows/analyze-test.yaml
The action was updated to remove `analysis-options-file`
=> Removed unsupported input

.github/workflows/release.yaml
This fixes https://github.com/linagora/linshare-mobile-flutter-app/issues/923
=> Added workflow step to create Github release

.github/workflows/release.yaml
=> Continue on error to release on Github

LICENSE
This follows LINAGORA Board of Director decision
=> Change license to AGPL V3

lib/l10n/intl_en.arb
=> Translated using Weblate (English)

android/fastlane/Fastfile, ios/fastlane/Fastfile
Prevent fastlane error when decrypting secrets
=> Auto update fastlane when running
