linagora/linshare-mobile-flutter-app

- domain/lib/src/usecases/file_picker/file_picker_view_state.dart
- lib/presentation/util/local_file_picker.dart
- lib/presentation/widget/myspace/my_space_widget.dart
- pubspec.yaml
Currently, after user go to pick file screen and then press cancel, failed upload message is toasted which should not happen. This PR is to fix it. 
I also remove unused `lang` folder in `pubspec`
@imGok @hoangdat please review this.
> Fix bug failed upload message toasted when user cancel pick file

- ios/Runner/Info.plist
@imGok @hoangdat @ngohado Please review this. I was fixing the following message from app store
> 
ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSPhotoLibraryUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their …
> LA-634: Add photo library usage description

- data/pubspec.yaml
- ios/Runner/Info.plist
- pubspec.yaml
Refer to this bug: [https://app.zenhub.com/workspaces/linshare-flutter-5fe04e3547c3510015c66915/issues/linagora/linshare-mobile-flutter-app/102undefined](https://app.zenhub.com/workspaces/linshare-flutter-5fe04e3547c3510015c66915/issues/linagora/linshare-mobile-flutter-app/102undefined)
> LA-102: avoid crash when upload multiple files in iOS

- pubspec.yaml
refer to this bug [https://github.com/linagora/linshare-mobile-flutter-app/issues/97](https://github.com/linagora/linshare-mobile-flutter-app/issues/97)
Seems like new version of `receive_sharing_intent 1.4.3` is not stable yet. can not receive sharing files outside. So I config to use `1.4.1` only
> LA-97: update receive_sharing_intent library version syntax

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- doc/adr/0008-upgrade-android-target-sdk-29.md
- pubspec.yaml
- Upgrade to Android target SDK 29
- Upgrade permission_handler lib to `5.1.0+2` 
Signed-off-by: Huy Nguyen <qhuynguyen@linagora.com>
> Upgrade to Android target SDK 29, upgrade permission_handler lib

- android/app/src/main/res/values/strings.xml
Convert download status message to uppercase
> LA-153 Fix Android notification status string

- data/lib/src/network/model/response/upload_request_group_response.dart
- domain/lib/src/model/upload_request_group/upload_request_group.dart
#559 
"maxFileSize" field is also optional it wasn't mentionned in the issue
> LA-559 Fix Upload Request Response Optional Field

- android/app/src/main/AndroidManifest.xml
- doc/adr/0002-receive-shared-file-from-other-app.md
- doc/adr/0010-migrate-to-null-safety-support.md
- ios/LinshareShareExtension/ShareViewController.swift
- ios/Runner/Info.plist
- lib/presentation/widget/upload_file/upload_file_manager.dart
- pubspec.yaml
- Ticket: #592 
- Problem resolved:
- Fix: Failed to share file from other app
- Fix: Upgrade to null-safety version; the backlog problem (migrating null-safety) here: https://github.com/linagora/linshare-mobile-flutter-app/commit/24356e0382b3c4c40469d702a232d6315d5ffbfd
- Fix: Share intent cause instance for Android
- Demo:
https://user-images.githubusercontent.com/29337364/133189410-470b0c14-ab46-4165-a414-d57d55b71538.mp4
> LA-592 Bug fixes Failed to share file from other app

- lib/presentation/view/search/search_bottom_bar_builder.dart
- Ticket: #648 
- Demo: 
- Before:
- After:
**Note**: Because this widget is common. This will affect all other screens, such as MySpace, ReceivedShared...
> LA-648 Increase touch area of search button

- domain/lib/src/model/sharedspacedocument/work_group_document.dart
- lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart
- Ticket: #653 
- Note:
- The root cause is that:
- After refreshing the list (online), the `parentWorkGroupNodeId` will be updated from server, so this makes it `NOT NULL`
- In the offline env, this function [`getListWorkGroupCacheInSharedSpace`](https://github.com/linagora/linshare-mobile-flutter-app/blob/1867058e16229403ce9e19777571b11dbf567251/data/lib/src/local/shared_space_document_database_manager.dart#L139) is checking `parentNodeId` nullable. So, the file is not fit the condition -> it will not appear on the list.
- Solution:
- When refreshing the list, we will not update the `parentWorkGroupNodeId` value from server into local database. Instead of that, we keep the current `parentWorkGroupNodeId` value. This only happens to database, not affect current app data (in memory)
- …
> LA-653 Fix bug offline file lost in refreshing

- lib/presentation/view/custom_list_tiles/shared_space_member_list_tile_builder.dart
- Completed in previous PR [https://github.com/linagora/linshare-mobile-flutter-app/pull/781](https://github.com/linagora/linshare-mobile-flutter-app/pull/781)
- [BUG] Fix disable click member label show menu select workgroup role
https://user-images.githubusercontent.com/80730648/148030146-5cc07346-0fbd-4dce-b178-c2e5192782b5.mov
> LA-722 Delete member of a workgroup inside drive

- lib/presentation/util/extensions/linshare_node_type_extension.dart
[GitLab issue](https://ci.linagora.com/linagora/lgs/linshare/products/linshare-ui-user/-/issues/1217)
updated the `create workspace` button translation key, from `create_workspace` to `create_new_workspace`
> 🐛 Fix:  Fixed wrong create workspace button text translation key (#1217)

- data/lib/src/network/model/response/document_details_response.dart
- data/lib/src/network/model/response/document_response.dart
- domain/lib/src/model/document/document.dart
- domain/lib/src/model/document/document_details.dart
- lib/presentation/model/file/document_presentation_file.dart
- lib/presentation/redux/states/functionality_state.dart
- lib/presentation/widget/myspace/document_details/document_details_widget.dart
[GitLab issue](https://ci.linagora.com/linagora/lgs/linshare/products/linshare-ui-user/-/issues/1220)
Wrong Key for expiration date in document_details
The expiration date doesn't take into consideration undefined expiration date
Called the right expiration date key in document_details
Added handling for null expiration_date
> Fixed wrong file expiration date in mySpace

- data/lib/src/datasource_impl/document_datasource_impl.dart
[GitLab issue](https://ci.linagora.com/linagora/lgs/linshare/products/linshare-ui-user/-/issues/1201)
Flutter_downloader requires `saveInPublicStorage` flag to be set to true for devices with android version greater than android Q(10) to be able to save in downloads folder
Set the `saveInPublicStorage` flag to `true` in  the  Flutter_Downloader call in `Download_document method`
> Fixed download not working from mySpace and shared space

- data/lib/src/datasource_impl/authentication_datasource_impl.dart
- data/lib/src/network/config/retry_authentication_interceptors.dart
- domain/lib/domain.dart
- domain/lib/src/errorcode/business_error_code.dart
- domain/lib/src/model/linshare_error_code.dart
- domain/lib/src/usecases/authentication/get_authorized_user_interactor.dart
- domain/lib/src/usecases/authentication/remove_permanent_token_interactor.dart
- lib/presentation/di/module/app_module.dart
- lib/presentation/di/module/widget_module.dart
- lib/presentation/widget/authentication/authentication_viewmodel.dart
[gitlab ticket](https://ci.linagora.com/linagora/lgs/linshare/products/linshare-ui-user/-/issues/1238)
When the permanent token is deleted from the web, the app gets stuck loading
when the permanent token is deleted the `RetryAuthenticationInterceptors` fails to get a new token and throws an unhandled exception causing the app to get stuck loading
- wrapping the code in the interceptor in try catch block 
- logout the user locally to prevent the account from getting locked
> Bug fix/cannot login when token is deleted

- data/lib/src/datasource_impl/shared_space_document_datasource_impl.dart
[GitLab issue](https://ci.linagora.com/linagora/lgs/linshare/products/linshare-ui-user/-/issues/1201)
Flutter_downloader requires `saveInPublicStorage` flag to be set to true for devices with android version greater than android Q(10) to be able to save in downloads folder
Set the `saveInPublicStorage` flag to `true` in  the  Flutter_Downloader call in `Download_document method`
> Fixed donwloads in sharedSpace

- lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart
[gitlab issue](https://ci.linagora.com/linagora/lgs/linshare/products/linshare-ui-user/-/issues/1272)
when `workgroupNode` is null the code return an empty string without performing the other tests
https://github.com/linagora/linshare-mobile-flutter-app/assets/160496984/c0859c85-4dbd-428a-8df3-f1f277448a37
changed the condition to allow other test to be performed
https://github.com/linagora/linshare-mobile-flutter-app/assets/160496984/9c78b1e6-08e3-485d-bbeb-18bb6ccb88e5
> Fixed can create file with empty or special chars name

- lib/presentation/widget/upload_request_creation/upload_request_creation_widget.dart
[gitlab issue](https://ci.linagora.com/linagora/lgs/linshare/products/linshare-ui-user/-/issues/1295)
Wrong attribute is used to determine if the checkbox should be displayed or not
Changed the attribute to `protectPasswordSetting` instead of  `passwordProtected`
> LA-1295 Fixed missing password protected checkbox

- data/lib/src/util/oidc_parser.dart
[gitlab issue](https://ci.linagora.com/linagora/lgs/linshare/products/linshare-ui-user/-/issues/1296)
when trying to login using sso with oidc-jwt the authentication fails
The `oidc_parser` is comparing to a wrong value for oidc token type `JWT` instead of  `Oidc-Jwt` so it's always defaulting to using `Oidc-opaque`
Changed to the right value
> LA-1296 changed key value for oidc-Jwt

- lib/presentation/widget/received_share_details/received_share_details_widget.dart
[GitLab issue](https://ci.linagora.com/linagora/lgs/linshare/products/linshare-ui-user/-/issues/1351)
the field `creationDate` is used instead of `expirationDate`
> LA-1351 fixed wrong expiration date in recieved shares

- data/lib/src/datasource_impl/received_share_datasource_impl.dart
[gitlab ticket](https://ci.linagora.com/linagora/lgs/linshare/products/linshare-ui-user/-/issues/1357)
when trying to download files from recieved shares the download fails
the parameter `saveInPublicStorage` needs to be set to true to save files in donwloads folder
[Received_share_download.webm](https://github.com/user-attachments/assets/14ac9d46-8556-4ecf-8f55-7a931d927045)
> LA-1357 fixed downloads failing for recieved shares

- lib/presentation/util/extensions/linshare_node_type_extension.dart
- lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart
Currently Workgroups workspaces and folders can be named and renamed with a dot at the end
There should be an error message: Folder name cannot finishes by character "."
added validation for this case
[dot.webm](https://github.com/user-attachments/assets/8916bcb0-884f-463e-b1ef-fabae7cfabed)
> LA-1358: Add validation for names ending with dot in workspace, workgroup, and folder for creation/editing

- lib/presentation/localizations/app_localizations.dart
- lib/presentation/util/toast_message_handler.dart
- lib/presentation/widget/shared_space_document/shared_space_node_versions/shared_space_node_versions_viewmodel.dart
When i delete the last version of a file its deleted
When I delete the final version of a file, there will be a message: You can't delete the last version, try to delete the whole document
https://github.com/user-attachments/assets/64f4ac65-4b46-4b64-8dfa-3bd2a78c2b45
> LA-1354 removed deleting last version of a file

- data/lib/src/datasource/received_share_datasource.dart
- data/lib/src/datasource_impl/local_received_share_datasource.dart
- data/lib/src/datasource_impl/received_share_datasource_impl.dart
- data/lib/src/extensions/user_extension.dart
- data/lib/src/local/received_share_database_manager.dart
- data/lib/src/repository/received/received_share_repository_impl.dart
- data/test/local/received_share_database_manager_test.dart
- domain/lib/domain.dart
- domain/lib/src/extension/received_share_extensions.dart
- domain/lib/src/repository/received/received_share_repository.dart
- domain/lib/src/usecases/received/get_all_received_shares_interactor.dart
- domain/lib/src/usecases/received/make_received_share_offline_interactor.dart
- domain/lib/src/usecases/received/remove_deleted_received_share_from_local_database.dart
- domain/test/usecases/received/get_all_received_interactor_test.dart
- lib/presentation/di/module/app_module.dart
- lib/presentation/widget/received/received_share_viewmodel.dart
- When saving received shares in the local database, the recipient's information is not tracked. As a result, when retrieving all received shares, documents that were saved by other users on the same device are mistakenly included in the  received shares list.
- When a received share is deleted or expires, it still remains present in the local database, leading to the display of unavailable documents in the received shares list in offline mode
- Added recipient information when saving received shares to the local database when data is retrieved.
- Added test for expiration date while retrieving
- Implemented an interactor to remove received shares from the local database when they are no longer available (deleted or expired)
[1352.webm](https://github.com/user-attachments/assets/c05badb4-3 …
> LA 1352 new files appear in offline mode

- lib/l10n/intl_en.arb
- lib/l10n/intl_messages.arb
- lib/presentation/localizations/app_localizations.dart
- lib/presentation/widget/edit_upload_request/edit_upload_request_viewmodel.dart
- lib/presentation/widget/upload_request_creation/upload_request_creation_viewmodel.dart
- The current conditions compare values that might be in different units
- The error message contains a hardcoded value of 100GB, which might not reflect the actual limit.
- Converted both the input value and limit to bytes before comparing.
- Added parameters for the l10n string to display the actual limit.
https://github.com/user-attachments/assets/fd3e6991-f393-4b5a-8764-524e0a810cae
> LA-1355 fix upload request total max size

- lib/presentation/localizations/app_localizations.dart
- lib/presentation/util/audio_recorder.dart
- lib/presentation/util/local_file_picker.dart
- lib/presentation/util/media_picker_from_camera.dart
- lib/presentation/util/permission_service.dart
- lib/presentation/view/dialog/permission_dialog.dart
- lib/presentation/widget/myspace/my_space_viewmodel.dart
- lib/presentation/widget/record_audio/record_audio_viewmodel.dart
- lib/presentation/widget/record_audio/record_audio_widget.dart
- lib/presentation/widget/shared_space_document/shared_space_document_viewmodel.dart
- lib/presentation/widget/shared_space_document/shared_space_document_widget.dart
- lib/presentation/widget/upload_file/upload_file_viewmodel.dart
- lib/presentation/widget/upload_file/upload_file_widget.dart
- lib/presentation/widget/upload_request_creation/upload_request_creation_viewmodel.dart
- lib/presentation/widget/upload_request_creation/upload_request_creation_widget.dart
- lib/presentation/widget/upload_request_group_add_recipient/add_recipients_upload_request_group_viewmodel.dart
- lib/presentation/widget/upload_request_group_add_recipient/add_recipients_upload_request_group_widget.dart
- #971
- added dialog to explain the use of contacts permission before requesting it
https://github.com/user-attachments/assets/b76b944e-840a-432e-8dea-7f9123a8ab6e
> LA-971 added explanation for contact permission
